import type { Metadata } from "next";
import { Noto_Sans, Overpass_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const notoSans = Noto_Sans({
  variable: "--font-Noto_Sans",
  subsets: ["latin"],
});

const overpassMono = Overpass_Mono({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-overpass-mono',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.className} antialiased`}
      >
        <Header font={overpassMono.className}/>
          {children}
        <Footer purpleFont={overpassMono.className}/>
      </body>
    </html>
  );
}
